# simplecov-erb formatter

language: ruby
install: true
script: "script/cibuild"

matrix:
  include:
    - rvm: 2.5
      env: SKIP_RUBOCOP=""
    - rvm: 2.1
      env: SKIP_RUBOCOP="true"
    - rvm: 2.0
      env: SKIP_RUBOCOP="true"
    - rvm: 1.9
      env: SKIP_RUBOCOP="true"
