name: stable

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.5.8, 2.6.6, 2.7.1, jruby-9.2.11.1]

    steps:
      - uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Get sqlite for Rails test projects
        run: sudo apt-get install libsqlite3-dev

      - name: Install bundler
        run: gem i bundler

      - name: Install dependencies
        run: script/bootstrap

      - name: Run tests (MRI)
        run: script/cibuild
        if: "!startsWith(matrix.ruby, 'jruby')"

      - name: Run tests (JRuby)
        run: JRUBY_OPTS=--debug script/cibuild
        if: startsWith(matrix.ruby, 'jruby')
